require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/*
  NewCops: enable
  TargetRubyVersion: 2.6

# x and y are descriptive enough variable names in the context of positions on a grid.
Naming/MethodParameterName:
  AllowedNames:
    - x
    - y

# Allow grouping a few related expectations together into a single example.
RSpec/MultipleExpectations:
  Max: 3
