require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/*
  NewCops: enable
  TargetRubyVersion: 2.6

# This makes long method chains look neater when running through the auto-correct.
Layout/DotPosition:
  EnforcedStyle: trailing

# RSpec has all of the tests for a class inside a single block, so these can legitimately get quite long.
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

# x and y are descriptive enough variable names in the context of positions on a grid.
Naming/MethodParameterName:
  AllowedNames:
    - x
    - y

# Allow grouping a few related expectations together into a single example.
RSpec/MultipleExpectations:
  Max: 3

# An extra level of nesting allows better reuse between specs.
RSpec/NestedGroups:
  Max: 4
