require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/*
  NewCops: enable
  TargetRubyVersion: 2.6

# Allow grouping a few related expectations together into a single example.
RSpec/MultipleExpectations:
  Max: 3
