#!/usr/bin/env ruby
# frozen_string_literal: true

require 'mission_to_mars'

if ARGV.empty?
  puts 'usage: mars <input path>'
  exit(1)
end

runner = MissionToMars::Runner.new(path: ARGV.fetch(0))
runner.run
